name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Run tests
        run: make test
